language: ruby
cache: bundler

rvm:
  - 2.2
  - 2.3.3
  - 2.4.1
  - ruby-head

before_install:
     - gem update bundler

script: bundle exec rake spec

notifications:
  irc: "irc.freenode.org#tdiary"

matrix:
  allow_failures:
    - rvm: ruby-head
