language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head


script: bundle exec rake spec

notifications:
  irc: "irc.freenode.org#tdiary"

matrix:
  allow_failures:
    - rvm: ruby-head
